RFC017: Service discovery
nuts-foundation/nuts-specification pull request #162
Opened 2022-01-07 10:28 UTC by reinkrul

Questions to answer:

- [ ]  What if a node were to publish a competitor's NutsComm endpoint in its DID document, causing implementations to ignore the competitor's endpoint (because the malicious node's DID document is processed first)

2022-01-14 10:55 UTC, woutslakhorst commented
> What if a node were to publish a competitor's NutsComm endpoint in its DID document, causing implementations to ignore the competitor's endpoint (because the malicious node's DID document is processed first). Maybe verify the NutsComm endpoint against the TLS certificate, so it can't be spoofed?

The connection would error since the SAN from the certificate doesn't match => log and remove from wanted connection list.

2022-01-14 10:56 UTC, woutslakhorst requested changes

2022-01-14 10:56 UTC, woutslakhorst commented on rfc/rfc017-distributed-network-grpc-v2.md
> +This SHOULD be done after the initial DAG sync is completed, to avoid connecting to non-existing endpoints resolved from older versions of DID documents.
NutsComm services with references to other DID Documents MUST be ignored. Only consider concrete endpoints.

2022-01-14 10:56 UTC, woutslakhorst commented
The other 2 points can be handled when a partial mesh is supported.

2022-10-24 11:14 UTC, woutslakhorst commented
@reinkrul status?

2022-10-24 11:20 UTC, reinkrul commented
> @reinkrul status?

Review vs. current implementation, update, review, merge

2023-03-06 12:26 UTC, gerardsn commented
@reinkrul Updated to describe service discovery as it is implemented

2023-03-06 13:56 UTC, woutslakhorst approved these changes

2023-03-06 14:52 UTC, gerardsn commented
Where should this go in the document? Probably §4 or §10, but I also see a case for generalizing the header of §3 and adding service discovery plus #254 there (if only because it is the smallest change to header numbers in a released version of this spec)

2023-03-09 09:30 UTC, reinkrul commented
Contents look OK, but propose includiong it in #255 and closing this PR

2023-03-09 15:36 UTC, gerardsn commented
superseded by #255

2023-03-09 15:36 UTC, closed without merging