added RFC018
nuts-foundation/nuts-specification pull request #171
Opened 2022-03-11 09:28 UTC by woutslakhorst

It describes the NutsConsentCredential for the paper use case.

There's also a small change to the NutsAuthorizationCredential. The NutsConsentCredential would be the preferred way to record consent evidence. The NutsAuthorizationCredential should then point to there.

The oid from BSN has also been removed since this can be solved by the JSON-LD type of the specific field.

2022-03-15 13:00 UTC, reinkrul requested changes

2022-03-16 12:04 UTC, woutslakhorst commented on rfc/rfc014-authorization-credential.md
> +When `legalBase.consentRef` is filled, it MUST point to a verifiable credential proving the subject gave consent.
It MUST be a reference to a VC which defines the format?

2022-03-16 12:06 UTC, woutslakhorst commented on rfc/rfc014-authorization-credential.md
> +When `legalBase.consentRef` is filled, it MUST point to a verifiable credential proving the subject gave consent.
That's all up to the issuer. The issuer has the obligation to provide the proof, not doing so can cause problems to the organization. Should the holder care about that? It'll not do anything with the referenced VC.

2022-03-16 12:09 UTC, woutslakhorst commented on rfc/rfc018-concent-credential.md
> +The Nuts Consent Credential allows for the actor to be a witness to the patient's consent. The resulting credential can then be send to the custodian (via a Verifiable Presentation for example). The
Another term would be `registrator`, the one who administers the consent?

2022-03-16 12:11 UTC, woutslakhorst commented on rfc/rfc018-concent-credential.md
> +The `issuer` field of the credential MUST contain the DID of the actor (also the witness). The `type` MUST include both the values `VerifiableCredential` and `NutsConsentCredential`. A Bolt specifica
In theory it could include other stuff as well. Those types are needed for the correct JSON-LD context selection.

2022-03-16 12:13 UTC, woutslakhorst commented on rfc/rfc018-concent-credential.md
> +The `credentialSubject` field contains the following:
Hmmm must have been an oversight.

2022-03-16 12:16 UTC, woutslakhorst commented on rfc/rfc018-concent-credential.md
> +A Nuts Consent Credential is private and is intended to be used by the holder when needed. In most cases the issuer will also be the holder. The VC MUST not be published on the network. Every DID MAY
When the client does it via PGO, but I'll remove it since it doesn't add anything.

2022-03-16 12:17 UTC, woutslakhorst commented on rfc/rfc018-concent-credential.md
> +The VC MUST contain two proofs. One proof will be a proof as described by [RFC011](rfc011-verifiable-credential.md). This is the proof the issuer has witnessed the contents and signs it with its asse
changed to verified

2022-03-16 12:19 UTC, woutslakhorst commented on rfc/rfc018-concent-credential.md
> +The `type` MUST be `NutsPaperProof2022`. `created` MUST be a valid datetime. The `expires` field is optionally. If filled, the `expirationDate` of the credential MAY NOT exceed this date. The `descri
That could actually be the case. It's a paper process, so when asked the paper should be presented.

2022-03-16 12:20 UTC, woutslakhorst commented on rfc/rfc018-concent-credential.md
> +The Nuts Authorization Credential only impacts the actor and custodian. It MUST be trusted automatically.
Then it would be the subject, added `subject` as party as well. But auto-trust still applies.

2022-03-16 12:21 UTC, woutslakhorst commented on rfc/rfc018-concent-credential.md
> +The Nuts Consent Credential MAY be used in any BOLT that requires Nuts Authorization Credentials based on implicent consent.
geh, funny

2022-03-17 12:46 UTC, reinkrul commented
Don't forget to update the getting started docs when the `NutsAuthorizationCredential` format changes

2022-03-21 08:24 UTC, stevenvegt commented on rfc/rfc018-concent-credential.md
> +}
Add a `expire` to the `credentialSubject`. It is is also in the signature, but that is imho about the signature and not about the actual consent.

2022-03-21 08:26 UTC, stevenvegt reviewed
Perhaps we should elevate it to a NutsLegalBaseCredential.
It can contain the consent of the subject but can also be a statement that the consent is implied, etc. Basically one of the 6 legal bases for information exchange:

1. toestemming van de betrokkene
2. uitvoeren van een overeenkomst
3. wettelijke verplichting
4. vitaal belang van de betrokkene
5. uitvoeren van een publiekrechtelijke taak
6. gerechtvaardigd belang van de organisatie

This way we can also use it for a 'emergency' case, or a gerechtelijk bevel.

2022-03-21 09:35 UTC, woutslakhorst commented
Will update to LegalBaseCredential and add examples for other GDPR cases.

2022-03-21 09:40 UTC, woutslakhorst commented
`subject` can be changed to something more BSNy

2022-10-24 06:32 UTC, stevenvegt commented
The VC spec now has an extra "evidence" chapter which seems to match our use-case with the `DocumentVerification` type https://www.w3.org/TR/vc-data-model/#evidence

2022-12-21 14:54 UTC, woutslakhorst commented
stale but not forgotten

2022-12-22 08:27 UTC, jorritspee commented
Hi,
For the Babyconnect use case one of the flows that the care providers want to support is:
1. Custodian (care provider B) registers explicit generic consent (1 bsn, 1 custodian, all future actors, all future use cases, all necessary resources)
2. This explicit generic consent (they call it DHT "Dossierhouderstoestemming") can not be automatically translated to specific NutsAuthorizationCredentials
3. When an actor (care provider A) wants to view data from care provider B, he asks the client: "what care providers have registered medical data from you?"
4. The client says: "care provider B"
5. Care provider A does not have a NutsAuthorizationCredential but he knows he can ask care provider B.
6. Care provider A sends a "NutsAuthorizationCredentialRequest" to a "AuthorizationCredentialRequest" endpont of Care provider B
7. Care provider B receivers the request and compares it tot the DHT registered in step 1
8. Care provider B decides to issue a NutsAuthorizationCredential to care provider A
9. From here on it's a normal Nuts-flow

This is different from RFC018, where consent is registered at the actor-side. Can you guys help us to standardize the above procedure?

2022-12-22 11:30 UTC, woutslakhorst commented
> This is different from RFC018, where consent is registered at the actor-side. Can you guys help us to standardize the above procedure?

Better to ask via Slack then this (unrelated) issue.

2023-01-04 09:03 UTC, jorritspee commented
> > This is different from RFC018, where consent is registered at the actor-side. Can you guys help us to standardize the above procedure?
> 
> Better to ask via Slack then this (unrelated) issue.

Okay, done. https://nuts-foundation.slack.com/archives/C01CH72S0AW/p1672822507233619

2023-05-01 06:49 UTC, woutslakhorst commented
Closing this, seems new OIDC specs will cover this.

2023-05-01 06:49 UTC, closed without merging