moved NutsAuthorizationCredential specific validations to RFC014
nuts-foundation/nuts-specification pull request #208
Opened 2022-09-05 09:37 UTC by woutslakhorst

closes #146

2022-09-06 04:57 UTC, reinkrul requested changes

2022-09-06 04:57 UTC, reinkrul commented on rfc/rfc014-authorization-credential.md
> +An NutsAuthorizationCredential is not needed when requester and authorizer are the same.
```suggestion
A `NutsAuthorizationCredential` is not needed when `requester` and `authorizer` are the same.
```

2022-09-07 12:30 UTC, gerardsn approved these changes

2022-09-08 07:21 UTC, reinkrul approved these changes

2022-09-12 07:39 UTC, merged