Remove algorithmic steps from RFC011
nuts-foundation/nuts-specification pull request #209
Opened 2022-09-07 14:52 UTC by stevenvegt

Fixes #160

2022-09-09 11:25 UTC, gerardsn reviewed
I don't know enough about the details to properly review this

2022-09-13 10:51 UTC, woutslakhorst approved these changes

2022-09-14 08:00 UTC, reinkrul requested changes

2022-09-14 08:00 UTC, reinkrul commented on rfc/rfc011-verifiable-credential.md
> +This signature suite is specified in [https://w3c-ccg.github.io/lds-jws2020](https://w3c-ccg.github.io/lds-jws2020). It uses a detached JWS for presenting the signature in the `jws` part of the proof
```suggestion
This signature suite is specified by [https://w3c-ccg.github.io/lds-jws2020](https://w3c-ccg.github.io/lds-jws2020). It uses a detached JWS for presenting the signature in the `jws` part of the proof. [RFC7797](https://tools.ietf.org/html/rfc7797) describes how a detached JWS works. The hashing algorithm should be of type `ES256`.
```

2022-09-14 08:00 UTC, reinkrul commented on rfc/rfc011-verifiable-credential.md
> +This signature suite is specified in [https://w3c-ccg.github.io/lds-jws2020](https://w3c-ccg.github.io/lds-jws2020). It uses a detached JWS for presenting the signature in the `jws` part of the proof
Hasing algorithm should be, or must be?

2022-09-19 13:50 UTC, merged