Rfc008 - Certificate structure
nuts-foundation/nuts-specification pull request #5
Opened 2020-10-14 07:17 UTC by woutslakhorst

Missing img:

![certificates_v1_alt](https://user-images.githubusercontent.com/703298/95956106-1e87c280-0dfe-11eb-8ee8-d944e2fb09ae.png)

2020-10-14 09:02 UTC, reinkrul requested changes

2020-10-15 06:40 UTC, woutslakhorst commented on rfc/rfc008-certificate-structure.md
> +When it comes to certificates, we’d like to be at the edge of usability and security. All administrative actions regarding keys should be simple and logical to the administrator and yet it should fol
changes solutions -> solution

2020-10-15 06:44 UTC, woutslakhorst commented on rfc/rfc008-certificate-structure.md
> +## Certificate Structure
We'll add the details for the data TLS connection to this RFC when it's ready. Main reason is that supporting the current rfc8 is doable for production but supporting the data TLS connection with client certificates is more problematic. Meaning we have do not comply with the rfc for a long time.

2020-10-15 06:57 UTC, woutslakhorst commented on rfc/rfc008-certificate-structure.md
> +* **document log**: data structure for the shared network state.
no longer needed

2020-10-15 07:01 UTC, woutslakhorst commented on rfc/rfc008-certificate-structure.md
> +The figure above shows the vendor CA tree. The lines indicate that a lower certificate is signed by a higher one in the graph. As can be seen, the vendor CA is the root of the tree. Each vendor MUST
Left it to RFC006 to explain the details

2020-10-15 07:13 UTC, woutslakhorst commented on rfc/rfc008-certificate-structure.md
> +The following paragraphs are more of a guideline than a hard requirement since it involves the internal workings of a node.
Not sure, I think we'll have to reevaluate this RFC when implementing it.

2020-10-15 07:13 UTC, woutslakhorst commented on rfc/rfc008-certificate-structure.md
> +## 3. Overview
Added some more intro text

2020-10-15 07:32 UTC, reinkrul approved these changes

2020-10-15 07:43 UTC, merged