RFC005: Specify TransactionList ordering
nuts-foundation/nuts-specification pull request #63
Opened 2021-05-04 08:21 UTC by reinkrul

Because out-of-order makes it very hard to process on the receiver's end.

2021-05-04 09:31 UTC, woutslakhorst requested changes

2021-05-04 09:31 UTC, woutslakhorst commented on rfc/rfc005-distributed-network-using-grpc.md
> +Since all referred to transactions (through `prev`) MUST be present, nodes MUST make sure to synchronize the oldest block first.
`referred to` -> `referenced`?

> Synchronize oldest **block** first

You mean **transactions**?

2021-05-06 12:06 UTC, stevenvegt approved these changes

2021-05-07 06:47 UTC, stevenvegt approved these changes

2021-05-10 07:10 UTC, woutslakhorst approved these changes

2021-05-11 05:56 UTC, merged